DROP TABLE IF EXISTS Projects CASCADE;


CREATE TABLE Projects(
    id SERIAL PRIMARY KEY NOT NULL,
    user_id INTEGER REFERENCES Users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    budget BIGINT NOT NULL,
    address VARCHAR(255) NOT NULL,
    status BOOLEAN NOT NULL,
    created_at TIMESTAMP(0) WITH TIME zone NOT NULL
);
