DROP TABLE IF EXISTS Bids CASCADE;

CREATE TABLE Bids (
  id SERIAL PRIMARY KEY NOT NULL,
  project_id INTEGER REFERENCES Projects(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES Users(id) ON DELETE CASCADE,
  amount BIGINT NOT NULL,
  status VARCHAR(50) NOT NULL,
  notes VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
