DROP TABLE IF EXISTS Payments CASCADE;

CREATE TABLE Payments(
    id SERIAL PRIMARY KEY NOT NULL,
    bid_id INTEGER REFERENCES Bids(id) ON DELETE CASCADE,
    status BOOLEAN NOT NULL,
    created_at TIMESTAMP(0) WITH TIME zone NOT NULL
);
